 const TEXT = {
  en: {
    coke: "Coca Cola",
    diet_coke: "Diet Coca Cola",
    water: "Water",
    green_tea: "Green Tea",
    milkis: "Milkis",
    banana_milk: "Banana Milk",
    kimchi: "Kimchi",
    rice: "White Rice",
    sprouts: "Seasoned Soybean Sprouts",
    cucumber: "Spicy Cucmber Salad",
    shin: "Shin Red (Spicy Beef)",
    shin_black: "Shin Black (Beef Bone Broth)",
    buldak: "Buldak (Spicy Chicken)",
    chapagetti: "Chapagetti (Jjajang Noodles)",
    pork: "Pork Belly",
    egg: "Soft Boiled Egg",
    bean_sprout: "Bean Sprout",
    fish_cake: "Fish Cake",
    seaweed: "Seaweed",
    green_onion: "Green Onion",
    submit_order: "Place your order",
    empty_cart: "Cart Is Empty",
    submitted_text: "Your order has been successfully submitted!",
    add: "Add",
  },
  ko: {
    coke: "코카콜라",
    diet_coke: "다이어트 코카콜라",
    water: "물",
    green_tea: "녹차",
    milkis: "밀키스",
    banana_milk: "바나나 우유",
    kimchi: "김치",
    rice: "밥",
    sprouts: "콩나물 무침",
    cucumber: "오이무침",
    shin: "신 레드 (매운 쇠고기)",
    shin_black: "신 블랙 (사골육수)",
    buldak: "불닥",
    chapagetti: "짜파게티",
    pork: "삼겹살",
    egg: "부드러운 삶은 계란",
    bean_sprout: "콩나물",
    fish_cake: "어묵",
    seaweed: "김",
    green_onion: "파",
    submit_order: "주문 제출",
    empty_cart: "카트가 비어 있습니다",
    submitted_text: "귀하의 주문이 성공적으로 제출되었습니다!",
    add: "추가하다",
  }
}